Traceback (most recent call last):
  File "main.py", line 5, in <module>
ModuleNotFoundError: No module named 'PyQt6'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
ModuleNotFoundError: No module named 'PyQt6'
Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "downloader.py", line 2, in <module>
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "main.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "downloader.py", line 2, in <module>
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "main.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "start.py", line 4, in <module>
ModuleNotFoundError: No module named 'win32con'
Traceback (most recent call last):
  File "main.py", line 1071, in <module>
  File "main.py", line 1052, in main
  File "main.py", line 677, in __init__
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "tg_log_full.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "tg_sender.py", line 3, in <module>
ModuleNotFoundError: No module named 'telegram'
Traceback (most recent call last):
  File "main.py", line 394, in initialize_managers_and_services
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "discord.py", line 6, in <module>
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "main.py", line 400, in initialize_managers_and_services
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "discord.py", line 6, in <module>
ModuleNotFoundError: No module named 'psutil'
